//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GivenNotGiven
    {
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Sem { get; set; }
        public string Section { get; set; }
        public Nullable<int> Given { get; set; }
        public Nullable<int> NotGiven { get; set; }
    }
}
