//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubComb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubComb()
        {
            this.NEW_RID_TABLE = new HashSet<NEW_RID_TABLE>();
        }
    
        public string CombId { get; set; }
        public string TID { get; set; }
        public string SubCode { get; set; }
        public int Sem { get; set; }
        public string DeptId { get; set; }
        public string Section { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public Nullable<bool> Elective { get; set; }
        public int Count { get; set; }
        public Nullable<decimal> Percentile { get; set; }
        public Nullable<int> ClassesHeld { get; set; }
        public Nullable<bool> isValid { get; set; }
    
        public virtual DEPT DEPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEW_RID_TABLE> NEW_RID_TABLE { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
